version: "2"
services:
    nodejs_devc:
        image: nodejs_devc
        build:
            context: nodejs_devc
            dockerfile: Dockerfile_dev_mac
        # コンテナ内のユーザーIDとグループIDを指定
            args:
                USER_UID: ${UID}
                USER_GID: ${GID}
        # 実行ユーザーを指定
        user: "${UID}:${GID}"
        environment:
            - TZ=${TZ}
            - UID=${UID}
            - GID=${GID}
        stdin_open: true
        # 開発用にソースコードをマウント
        volumes:
            - ./nodejs_devc/app/src/:/app/src/