kind: Namespace
apiVersion: v1
metadata:
  name: test-nginx
  labels:
    name: test-nginx-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx-deployment
  namespace: test-nginx
spec:
  selector:
    matchLabels:
      app: test-nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: test-nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  namespace: test-nginx
  name: test-nginx-service
spec:
  selector:
    app: test-nginx
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31080
