apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    datastore: redis
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        datastore: redis
    spec:
      containers:
        - image: kube1:30500/datastore/redis
          name: redis
          ports:
          - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  labels:
    datastore: redis
  name: redis
spec:
  type: NodePort
  ports:
  - name: "redis-access"
    port: 6379
    targetPort: 6379
    protocol: TCP
    nodePort: 30379
  selector:
    datastore: redis
