version: '2'

services:
    nginx_proxy:
        image: nginx_proxly
        build: nginx_custom
        restart: always
        ports:
            - "80:80"
            - "443:443"
        networks:
            - default
            - redmine_default
            #- zabbix_default
            - unit_default
            # - gitlab_default
networks:
    redmine_default:
        external: true
    #zabbix_default:
    #    external: true
    unit_default:
        external: true

    # gitlab_default:
    #    external: true
