version: '2'

services:
    Redis:
        image: redis_custom
        build: redis_custom
        restart: always
        ports:
            - "6379:6379"
        networks:
            - default
    redisCommander:
        image: tenstartups/redis-commander
        command: --redis-host Redis
        depends_on:
            - Redis
        ports:
            - "8082:8081"
