version: "3"
services:
  isomaker:
    image: isomaker
    build: isomaker
    #restart: always
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./isomaker/src:/usr/src/
    privileged: true