version: '2'

services:
    mariadb:
        image: mariadb
        build: mariadb_custom
        ports:
            - "3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: startup
        # volumes:
        #     - ./db_data:/var/lib/mysql
