services:
    caserver:
        image: easyrsa_c
        build:
            context: easyrsa_c
            args:
                CA_NOPASS: "true"
                CA_NAME: "SSCA"
                CA_KEYPASS: "password"

        # restart: always
