version: '3.5'
services:
    zabbix-ap:
        image: zabbix-appg
        build: zabbix-appg_custom
        ports:
            - "10051:10051"
        restart: always
        depends_on:
            - zabbix-timescaledb
        environment:
                TZ: Asia/Tokyo
                DB_SERVER_HOST: zabbix-timescaledb
                POSTGRES_USER: zabbix
                POSTGRES_PASSWORD: zabbix
                PHP_TZ: Asia/Tokyo
        # logging:
        #    driver: "json-file" # defaults if not specified
        #    options:
        #        max-size: "10m"
        #        max-file: "3"


    zabbix-web:
        image: zabbix-web_pg
        build: zabbix-webpg_custom
        restart: always
        ports:
            - "80"
            - "443"
        depends_on:
            - zabbix-timescaledb
            - zabbix-ap
        environment:
            TZ: Asia/Tokyo
            DB_SERVER_HOST: zabbix-timescaledb
            POSTGRES_USER: zabbix
            POSTGRES_PASSWORD: zabbix
            ZBX_SERVER_HOST: zabbix-ap
            PHP_TZ: Asia/Tokyo
        #logging:
        #    driver: "json-file" # defaults if not specified
        #    options:
        #        max-size: "10m"
        #        max-file: "3"


    zabbix-timescaledb:
        image: zabbix-timescaledb
        build: timescaledb_custom
        ports:
            - "5432"
        restart: always
        environment:
            TZ: Asia/Tokyo
            POSTGRES_DATABASE: zabbix
            POSTGRES_USER: zabbix
            POSTGRES_PASSWORD: zabbix
            POSTGRES_DB: zabbix
        #logging:
        #    driver: "json-file" # defaults if not specified
        #    options:
        #        max-size: "10m"
        #        max-file: "3"


        # volumes:
        #     - - ./db_data:/var/lib/postgresql/data
        # Log設定を追加
