version: '2'
services:
    # APIServer_nginx
    nginx_forunit:
        build: "nginx_custom"
        image: "nginx_forunit"
        # restart: "no"
        # expose:
        expose:
            - "80"
            - "443"
        depends_on:
            - "unitpy_api"

    # APIServer_unitpy_api
    unitpy_api:
        build: "unitpy_custom"
        image: "unitpy_api"
        restart: "no"
        expose:
            - "8300"

    unit_mariadb:
        build: mariadb_custom
        image: unit_mariadb
        ports:
            - "3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: unit
            MYSQL_DATABASE: unit
            MYSQL_USER: unit
            MYSQL_PASSWORD: unit
