version: "2"

services:
    nrproxy:
        image: nrproxy
        build: nrproxy
        restart: always
        ports:
            - "80:80"
            - "443:443"
        networks:
            - default
            # - OtherNW_default
#networks:
#OtherNW_default:
#    external: true
