version: '2'

services:
    redmine:
        image: redmine
        restart: always
        ports:
            - 80:3000
        depends_on:
            - redmine-db
        environment:
            REDMINE_DB_MYSQL: redmine-db
            REDMINE_DB_PASSWORD: redmine

    redmine-db:
        image: mariadb_redmine
        build: mariadb_custom
        # image: mysql:5.7
        # command: mysqld –character-set-server=utf8 –collation-server=utf8_unicode_ci
        ports:
            - 3306:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: redmine
            MYSQL_DATABASE: redmine
        # volumes:
        #     - ./mariadb_custom/data:/var/lib/mysql
