apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: local-registory
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: local-registory
    spec:
      containers:
        - name: local-registory
          image: registry
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: local-registory
spec:
  type: NodePort
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 32000
  selector:
    app: local-registory
