version: "3"

services:
  haskell_cplain:
    image: haskell_cplain
    build: .
    restart: "no"
    volumes:
      - ./code:/code
    user: "501:20"
    #ports:
    #  - "80:5000"
    environment:
      - TZ=Asia/Tokyo
