version: '2'
services:
    # APIServer_nginx
    nginx_for_unit:
        build: "nginx_custom"
        image: "nginx_for_unit"
        # restart: "no"
        # expose:
        expose:
            - "80"
            - "443"
        depends_on:
            - "unitpy_api"

    # APIServer_unitpy_api
    unitpy_api:
        build: "unitpy_custom"
        image: "unitpy_api"
        restart: "no"
        expose:
            - "8300"
