version: "3"
services:
  python:
    image: python_dev
    build: python_dev
    container_name: python_dev
    # ports:
    #  - "3000:3000"
    # restart: always
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./python_dev/src:/usr/src/
