FROM postgres
MAINTAINER y.yoshimoto

# 設定ファイルのコピー
# sample: /usr/share/postgresql/postgresql.conf.sample
# COPY postgresql.conf /etc/postgresql/postgresql.conf

# 初期構築データのコピー
# COPY startup.sql /docker-entrypoint-initdb.d/startup.sql
