version: '3'

services:
    web_container:
        image: web_container
        build: web_container
        restart: always
        ports:
            - "80:80"
            - "443:443"
        networks:
            - default

networks:
    redmine_default:
        external: true
    unit_default:
        external: true
