version: '3'

services:
    web_container:
        image: web_container
        build: web_container
        restart: always
        ports:
            - "80:80"
            - "443:443"
        networks:
            - default
        volumes:
             - ./web_container/contents/:/usr/share/nginx/html/