version: '3.1'

services:
    timescaledb:
        image: timescaledb
        build: timescaledb_custom
        ports:
            - 5432
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            #POSTGRES_USER:
        # volumes:
        #     - ./db_data:/var/lib/postgresql/data
#
