version: "3"

services:
  flaskapp:
    image: flaskapp
    build: flaskapp
    restart: always
    #volumes:
    #  - ./FlaskApp:/code
    ports:
      - "80:5000"
    environment:
      - TZ=Asia/Tokyo
