version: "3"

services:
  haskell_c:
    image: haskell_c
    build: haskell_c
    restart: "no"
    #volumes:
    #  - ./haskell_c:/code
    #ports:
    #  - "80:5000"
    environment:
      - TZ=Asia/Tokyo
