version: '2'

services:
    gitlab:
        image: gitlab_custom
        build: gitlab_custom
        restart: always
        #expose:
        #    - "80"
        #    - "443"
        #    - "22"
        ports:
            - "80:80"
        environment:
            external_url: 'http://127.0.0.1/gitlab'
            #external_url: 'http://127.0.0.1/'
            gitlab_rails['time_zone']: 'Asia/Tokyo'
            gitlab_rails['gitlab_shell_ssh_port']: 22
            gitlab_rails['relative_url_root']: /gitlab
