version: '2'

services:
    gitlab:
        image: gitlab_custom
        build: gitlab_custom
        # restart: always
        expose:
            - "80"
            - "443"
            - "22"
        # ports:
        #    - "80:80"
        environment:
            GITLAB_OMNIBUS_CONFIG : |
                external_url 'http://127.0.0.1/gitlab/'
                gitlab_rails['time_zone'] = 'Asia/Tokyo'
        # volumes:
        # - ./gitlab/config:/etc/gitlab
        # - ./gitlab/logs:/var/log/gitlab
        # - ./gitlab/data:/var/opt/gitlab
