version: "3"
services:
    express:
        build: express
        image: express
        restart: always
        ports:
            - "8040:8040"
        environment:
            TZ: "Asia/Tokyo"
        #volumes:
        #    - ./express/contents/:/www/Sample/
