version: '3.1'

services:
    postgres:
        image: postgres
        build: postgres_custom
        ports:
            - 5432
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            #POSTGRES_USER:
        # volumes:
        #     - ./db_data:/var/lib/postgresql/data
# https://hub.docker.com/_/postgres
#
