version: "3"
services:
  labelstudio:
    image: labelstudio_c
    build: labelstudio_c
    ports:
      - 8080:8080
    volumes:
      - ./labeldata:/label-studio/data
      - ./localImage:/localImage
    environment:
      - TZ=${TZ}
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/localImage
    command: label-studio start --username test@test.com --password password
  labelstudio_mlbackend:
    image: mlbackend_c
    build: mlbackend_c

volumes:
  labeldata:
