version: "3"
services:
  labelstudio:
    image: labelstudio_c
    build: labelstudio_c
    ports:
      - 8080:8080
    volumes:
      - ./labeldata:/label-studio/data
      - ./localImage:/localImage
    environment:
      - TZ=${TZ}
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/localImage
    command: label-studio start --username test@test.com --password password
  labelstudio_mlbackend:
    image: mlbackend_c
    build: mlbackend_c
    ports:
      - 9090:9090
    environment:
      - TZ=Asia/Tokyo
      - PYTHONDONTWRITEBYTECODE=1
      - LABEL_STUDIO_HOSTNAME=http://labelstudio:8080
      - LABEL_STUDIO_API_KEY=d6f8a2622d39e9d89ff0dfef1a80ad877f4ee9e3
      - LABEL_STUDIO_ML_BACKEND_V2=true
    volumes:
      - ./mlbackend_c/src:/usr/src
volumes:
  labeldata:
