version: "3"
services:
  labelstudio:
    image: labelstudio_c
    build: labelstudio_c
    ports:
      - 8080:8080
    volumes:
      - ./labeldata:/label-studio/data
      - ./localImage:/localImage
    environment:
      TZ: ${TZ}
      LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED: true
      LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT: /localImage
    command: label-studio start --username test@test.com --password password
  mlbackend:
    image: mlbackend_c
    build: mlbackend_c
    ports:
      - 9090:9090
    environment:
      TZ: Asia/Tokyo
      FLASK_ENV: development
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      LABEL_STUDIO_HOSTNAME: http://labelstudio:8080
      LABEL_STUDIO_API_KEY: dcd6e81405c5d8311ec6d96d989110a396e84174
      LABEL_STUDIO_ML_BACKEND_V2: true
      LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT: /localImage
      SCORE_THRESHOLD: 0.5
    volumes:
      - ./mlbackend_c/src:/usr/src
volumes:
  labeldata:
